baseURL = "https://anecdotas-bonsai.netlify.com/"
languageCode = "en-us"
title = "An√©cdotas Bonsai"
#theme = "mediumish"
#theme = "ananke"
theme = "basics"
#theme = "onepress"
#theme = "cactus-plus"
#theme = "kiss"
DisqusShortname = ""

[params]
	author = "Denat Idego"
